# Машинное обучение. ВМК МГУ

# Практическое задание 2: Numpy + pandas + matplotlib

## Уровень: **Исследовательский (Research)**

# О формате сдачи

🔷 При решении ноутбука используйте данный шаблон

```
✅ Можно добавлять новые ячейки любых типов
❌ Не нужно удалять текстовые ячейки c разметкой частей ноутбука и формулировками заданий
```

🔷 При оценивании задач учитывается код

```
✅ Задания, в которых необходим код, обычно помечаются фразами "Your code here"/"Ваш код" и аналогичными
❌ Ответы на вопросы без сопутствующего кода оцениваются в 0 баллов
❌ Наличе работоспособного кода в ноутбуке, если на сказано иного, обязательно
```

🔷 При оценивании задач учитываются выводы

```
✅ Задания, в которых необходимы выводы, обычно помечаются фразами Вывод"/"Ответ на вопрос"/"Ваш текст" и аналогичными
✅ Обычно выводы подразумевают под собой текстовый ответ (можно писать markdown, latex).
✅ Сопутствующие изображения, графики, таблички - приветствуются!
❌ При отсутствии выводов задание не засчитается на полный балл
```

- Многие из заданий можно выполнить несколькими способами.
Не существуют единственно верного, но попробуйте максимально
задействовать арсенал pandas и ориентируйтесь на простоту и понятность
вашего кода. Не забывайте, что можно гуглить и что-то искать на stackoverflow, например.

# Подготовка рабочей среды

Сначала установим нужные нам версии библиотек. Мы гарантируем, что в данных версиях задание будет корректно отрабатывать.

После установки нужных версий, возможно, нужно перезагрузить среду (runtime), но скорее всего вам это не понадобится

На скачивание файла и установку понадобится не более 5 минут.

**Важно!**

Устанавливать нужные версии нужно каждый раз, когда создается новый
рантайм. Например, если вы 2 часа подряд делаете это задание, то
подготовить библиотеки достаточно 1 раз. Но если вы, например, начали в
понедельник, затем закрыли/выключили ноутбук, то при продолжении в
среду, вам нужно будет запустить рантайм заново и следовательно заново
установить библиотеки.

**Важно!**
Если вы предпочитаете делать практические задания на своем личном ноутбуке, то проверьте, что вы установили рабочее окружение в соответствии с гайдом .pdf)

In [ ]:
# !!! Данный блок будет работать только в Google-Colab !!!
! gdown 10k8Hwn9kpK9SpK4IEj4-EaWQZqgYT5-Q
! pip install -r /content/requirements_2024_25_for_colab_small.txt

Downloading...
From: https://drive.google.com/uc?id=10k8Hwn9kpK9SpK4IEj4-EaWQZqgYT5-Q
To: /content/requirements_2024_25_for_colab_small.txt
100% 375/375 [00:00<00:00, 1.33MB/s]
Collecting catboost==1.2.7 (from -r /content/requirements_2024_25_for_colab_small.txt (line 1))
  Downloading catboost-1.2.7-cp310-cp310-manylinux2014_x86_64.whl.metadata (1.2 kB)
Collecting gdown==5.1.0 (from -r /content/requirements_2024_25_for_colab_small.txt (line 2))
  Downloading gdown-5.1.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: h5py==3.11.0 in /usr/local/lib/python3.10/dist-packages (from -r /content/requirements_2024_25_for_colab_small.txt (line 3)) (3.11.0)
Requirement already satisfied: hyperopt==0.2.7 in /usr/local/lib/python3.10/dist-packages (from -r /content/requirements_2024_25_for_colab_small.txt (line 4)) (0.2.7)
Collecting ipympl==0.9.4 (from -r /content/requirements_2024_25_for_colab_small.txt (line 5))
  Downloading ipympl-0.9.4-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: ipywidgets==7.7.1 in /usr/local/lib/python3.10/dist-packages (from -r /content/requirements_2024_25_for_colab_small.txt (line 6)) (7.7.1)
Collecting lightgbm==4.4.0 (from -r /content/requirements_2024_25_for_colab_small.txt (line 7))
  Downloading lightgbm-4.4.0-py3-none-manylinux_2_28_x86_64.whl.metadata (19 kB)
Requirement already satisfied: matplotlib==3.7.1 in /usr/local/lib/python3.10/dist-packages (from -r /content/requirements_2024_25_for_colab_small.txt (line 8)) (3.7.1)
Requirement already satisfied: matplotlib-inline==0.1.7 in /usr/local/lib/python3.10/dist-packages (from -r /content/requirements_2024_25_for_colab_small.txt (line 9)) (0.1.7)
Requirement already satisfied: numpy==1.26.4 in /usr/local/lib/python3.10/dist-packages (from -r /content/requirements_2024_25_for_colab_small.txt (line 10)) (1.26.4)
Collecting pandas==2.1.4 (from -r /content/requirements_2024_25_for_colab_small.txt (line 11))
  Downloading pandas-2.1.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting pep8==1.7.1 (from -r /content/requirements_2024_25_for_colab_small.txt (line 12))
  Downloading pep8-1.7.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting plotly==5.15.0 (from -r /content/requirements_2024_25_for_colab_small.txt (line 13))
  Downloading plotly-5.15.0-py2.py3-none-any.whl.metadata (7.0 kB)
Collecting pycodestyle==2.12.1 (from -r /content/requirements_2024_25_for_colab_small.txt (line 14))
  Downloading pycodestyle-2.12.1-py2.py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: pytest==7.4.4 in /usr/local/lib/python3.10/dist-packages (from -r /content/requirements_2024_25_for_colab_small.txt (line 15)) (7.4.4)
Collecting scikit-image==0.23.2 (from -r /content/requirements_2024_25_for_colab_small.txt (line 16))
  Downloading scikit_image-0.23.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (14 kB)
Collecting scikit-learn==1.3.2 (from -r /content/requirements_2024_25_for_colab_small.txt (line 17))
  Downloading scikit_learn-1.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Requirement already satisfied: scipy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from -r /content/requirements_2024_25_for_colab_small.txt (line 18)) (1.13.1)
Collecting seaborn==0.13.1 (from -r /content/requirements_2024_25_for_colab_small.txt (line 19))
  Downloading seaborn-0.13.1-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: tqdm==4.66.5 in /usr/local/lib/python3.10/dist-packages (from -r /content/requirements_2024_25_for_colab_small.txt (line 20)) (4.66.5)
Collecting umap-learn==0.5.6 (from -r /content/requirements_2024_25_for_colab_small.txt (line 21))
  Downloading umap_learn-0.5.6-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: xgboost==2.1.1 in /usr/local/lib/python3.10/dist-packages (from -r /content/requirements_2024_25_for_colab_small.txt (line 22)) (2.1.1)
Requirement already satisfied: graphviz in /usr/local/lib/python3.10/dist-packages (from catboost==1.2.7->-r /content/requirements_2024_25_for_colab_small.txt (line 1)) (0.20.3)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from catboost==1.2.7->-r /content/requirements_2024_25_for_colab_small.txt (line 1)) (1.16.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from gdown==5.1.0->-r /content/requirements_2024_25_for_colab_small.txt (line 2)) (4.12.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from gdown==5.1.0->-r /content/requirements_2024_25_for_colab_small.txt (line 2)) (3.16.1)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.10/dist-packages (from gdown==5.1.0->-r /content/requirements_2024_25_for_colab_small.txt (line 2)) (2.32.3)
Requirement already satisfied: networkx>=2.2 in /usr/local/lib/python3.10/dist-packages (from hyperopt==0.2.7->-r /content/requirements_2024_25_for_colab_small.txt (line 4)) (3.3)
Requirement already satisfied: future in /usr/local/lib/python3.10/dist-packages (from hyperopt==0.2.7->-r /content/requirements_2024_25_for_colab_small.txt (line 4)) (1.0.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.10/dist-packages (from hyperopt==0.2.7->-r /content/requirements_2024_25_for_colab_small.txt (line 4)) (2.2.1)
Requirement already satisfied: py4j in /usr/local/lib/python3.10/dist-packages (from hyperopt==0.2.7->-r /content/requirements_2024_25_for_colab_small.txt (line 4)) (0.10.9.7)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.10/dist-packages (from ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (0.2.0)
Requirement already satisfied: ipython<9 in /usr/local/lib/python3.10/dist-packages (from ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (7.34.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (from ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (10.4.0)
Requirement already satisfied: traitlets<6 in /usr/local/lib/python3.10/dist-packages (from ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (5.7.1)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (5.5.6)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (3.6.9)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (3.0.13)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib==3.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 8)) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib==3.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 8)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib==3.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 8)) (4.54.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib==3.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 8)) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib==3.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 8)) (24.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib==3.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 8)) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib==3.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 8)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas==2.1.4->-r /content/requirements_2024_25_for_colab_small.txt (line 11)) (2024.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas==2.1.4->-r /content/requirements_2024_25_for_colab_small.txt (line 11)) (2024.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly==5.15.0->-r /content/requirements_2024_25_for_colab_small.txt (line 13)) (9.0.0)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.10/dist-packages (from pytest==7.4.4->-r /content/requirements_2024_25_for_colab_small.txt (line 15)) (2.0.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in /usr/local/lib/python3.10/dist-packages (from pytest==7.4.4->-r /content/requirements_2024_25_for_colab_small.txt (line 15)) (1.5.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /usr/local/lib/python3.10/dist-packages (from pytest==7.4.4->-r /content/requirements_2024_25_for_colab_small.txt (line 15)) (1.2.2)
Requirement already satisfied: tomli>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from pytest==7.4.4->-r /content/requirements_2024_25_for_colab_small.txt (line 15)) (2.0.2)
Requirement already satisfied: imageio>=2.33 in /usr/local/lib/python3.10/dist-packages (from scikit-image==0.23.2->-r /content/requirements_2024_25_for_colab_small.txt (line 16)) (2.35.1)
Requirement already satisfied: tifffile>=2022.8.12 in /usr/local/lib/python3.10/dist-packages (from scikit-image==0.23.2->-r /content/requirements_2024_25_for_colab_small.txt (line 16)) (2024.9.20)
Requirement already satisfied: lazy-loader>=0.4 in /usr/local/lib/python3.10/dist-packages (from scikit-image==0.23.2->-r /content/requirements_2024_25_for_colab_small.txt (line 16)) (0.4)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn==1.3.2->-r /content/requirements_2024_25_for_colab_small.txt (line 17)) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn==1.3.2->-r /content/requirements_2024_25_for_colab_small.txt (line 17)) (3.5.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.10/dist-packages (from umap-learn==0.5.6->-r /content/requirements_2024_25_for_colab_small.txt (line 21)) (0.60.0)
Collecting pynndescent>=0.5 (from umap-learn==0.5.6->-r /content/requirements_2024_25_for_colab_small.txt (line 21))
  Downloading pynndescent-0.5.13-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.10/dist-packages (from xgboost==2.1.1->-r /content/requirements_2024_25_for_colab_small.txt (line 22)) (2.23.4)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.5.1->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (6.1.12)
Requirement already satisfied: tornado>=4.2 in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.5.1->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (6.3.3)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.10/dist-packages (from ipython<9->ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (71.0.4)
Collecting jedi>=0.16 (from ipython<9->ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5))
  Using cached jedi-0.19.1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython<9->ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (from ipython<9->ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from ipython<9->ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (3.0.48)
Requirement already satisfied: pygments in /usr/local/lib/python3.10/dist-packages (from ipython<9->ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (2.18.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.10/dist-packages (from ipython<9->ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython<9->ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (4.9.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.10/dist-packages (from numba>=0.51.2->umap-learn==0.5.6->-r /content/requirements_2024_25_for_colab_small.txt (line 21)) (0.43.0)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.10/dist-packages (from widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (6.5.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->gdown==5.1.0->-r /content/requirements_2024_25_for_colab_small.txt (line 2)) (2.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown==5.1.0->-r /content/requirements_2024_25_for_colab_small.txt (line 2)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown==5.1.0->-r /content/requirements_2024_25_for_colab_small.txt (line 2)) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown==5.1.0->-r /content/requirements_2024_25_for_colab_small.txt (line 2)) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown==5.1.0->-r /content/requirements_2024_25_for_colab_small.txt (line 2)) (2024.8.30)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown==5.1.0->-r /content/requirements_2024_25_for_colab_small.txt (line 2)) (1.7.1)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython<9->ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (0.8.4)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (3.1.4)
Requirement already satisfied: pyzmq<25,>=17 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (24.0.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (23.1.0)
Requirement already satisfied: jupyter-core>=4.6.1 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (5.7.2)
Requirement already satisfied: nbformat in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (5.10.4)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (6.5.4)
Requirement already satisfied: nest-asyncio>=1.5 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (1.6.0)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (0.21.0)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (1.1.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython<9->ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython<9->ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (0.2.13)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.10/dist-packages (from jupyter-core>=4.6.1->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (4.3.6)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.10/dist-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (0.2.4)
Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (4.9.4)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (6.1.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (0.7.1)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (0.4)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (0.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (2.1.5)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (0.8.4)

Проверим версию библиотеки:

In [ ]:
import catboost
assert(catboost.__version__ == '1.2.7')

Теперь можно приступать к выполнению задания! :)

# О задании

Задание состоит из трех частей, посвященных работе с табличными данными с помощью библиотеки pandas , визуализации с помощью библиотек matplotlib , seaborn , plotly и векторным вычислениям с помощью библиотеки numpy . Вам предлагается выполнить несколько заданий.

# Часть 1. Pandas (3,5 балла), кросс-проверка

В этой части вы отработаете навыки работы с библиотекой **pandas** .

**Подсказка** Если вы еще не прошли выданный воркбук по pandas , то советуем в начале обратиться к нему. Также рекомендуем сначала решить базовую часть, прежде чем приступать к этой.

**Внимание!** Некоторые задачи требует дополнительного изучения документации, не стесняйтесь искать нужные методы в интернете

Далее потребуется выполнить несколько небольших заданий, покрывающих
базовый функционал библиотеки, который довольно часто пригождается на
первичных этапах анализа данных перед обучением ML-моделей.

In [ ]:
import pandas as pd

In [ ]:
!gdown 1sA-fqJb1WxhS_jaYDcIwXWa_b8b2oZJ6

Downloading...
From: https://drive.google.com/uc?id=1sA-fqJb1WxhS_jaYDcIwXWa_b8b2oZJ6
To: /content/youtube_trending_mediterranean.csv
100% 6.22M/6.22M [00:00<00:00, 203MB/s]

### **Задание 1 [0.5 баллa]**

Загрузите данные и посмотрите на колонку publishedAt

- **(0.1 балла)** Какого она типа?
- **(0.2 балла)** Измените тип колонки на datetime . Покажите, что после изменения колонка действительно имеет тип datetime .
- **(0.2 балла)** В какой месяц было добавлено больше всего видеороликов?

In [ ]:
df = pd.read_csv("youtube_trending_mediterranean.csv")
df.dtypes["publishedAt"]
df["publishedAt"]= pd.to_datetime(df["publishedAt"])
df['month'] = df['publishedAt'].dt.month
df_new = df.groupby('month').size()
df_new

,0
month,
6,1068
7,2153

**Тип publishedAt: object**
**, больше всего видео было добавлено в июле**

In [ ]:
df.drop('month', axis=1)

,country,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description
0,AL,hxWSp-8jJuo,DON XHONI - KATILE,2022-07-07 22:00:12+00:00,UCZNJXsf2I4y54M_UmMiC6Vw,DON XHONI,24,22.11.07,[none],5130167,3641,https://i.ytimg.com/vi/hxWSp-8jJuo/default.jpg,False,True,Stream or Download now ''KATILE'' ð https:/...
1,AL,MnrC9mk2H1o,Dhurata Dora x Elvana Gjata - GAJDE (Official ...,2022-06-30 22:00:11+00:00,UCtzhq8TIfFB9vRAHVqLL9PA,Dhurata Dora,10,22.11.07,[none],8886648,4414,https://i.ytimg.com/vi/MnrC9mk2H1o/default.jpg,False,True,The official video for GAJDE.Stream/Download G...
2,AL,5Ql-G0dTqC0,KIDA x BUTRINT IMERI - AM/PM,2022-07-02 22:00:11+00:00,UCAHVxL9FG3Sp8ltQtLEy_oA,KIDA,10,22.11.07,Butrint Imeri|Kida|Dale|Butrint imeri kida|But...,7230818,7518,https://i.ytimg.com/vi/5Ql-G0dTqC0/default.jpg,False,True,Stream or Download âAM/PMâ here ð§ https...
3,AL,oUdY0qSavvY,Dafina Zeqiri - Malli,2022-07-07 22:00:12+00:00,UCrv0PJoutcRhHkSMJYoXAIQ,Dafina Zeqiri,10,22.11.07,Dafina|Zeqiri|Dafine Moj|Pa ty|Lule Lule|Duro|...,1406078,827,https://i.ytimg.com/vi/oUdY0qSavvY/default.jpg,False,True,Bzzz Entertainment - https://lnk.to/BzzzStream...
4,AL,I4ZSvYLnOcQ,Tayna x Azet - Tequila,2022-06-30 18:00:26+00:00,UCJBZ-GcWSswmJ0xc9WAKDqw,Friends Entertainment,10,22.11.07,tayna|Friends|Entertainment|rinor hykolli|hip ...,6397676,6063,https://i.ytimg.com/vi/I4ZSvYLnOcQ/default.jpg,False,True,Stream âTequilaâ:https://taynaxazet.lnk.to...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3216,NaN,eB-A1Y0Dswc,Thank you for watching,2022-07-05 21:18:33+00:00,UCS5tt2z_DFvG7-39J3aE-bQ,Life of Boris,22,22.11.07,lifeofboris|life of boris|english subtitles|ye...,864216,14431,https://i.ytimg.com/vi/eB-A1Y0Dswc/default.jpg,False,True,New channel: https://www.youtube.com/channel/U...
3217,NaN,KJGTtzccOHU,Pokemon Emerald but every battle is extremely ...,2022-07-05 01:55:10+00:00,UC0VVYtw21rg2cokUystu2Dw,SmallAnt,20,22.11.07,pokemon|smallant|smallant1|challenge|pokemon c...,1311698,1232,https://i.ytimg.com/vi/KJGTtzccOHU/default.jpg,False,True,Pokemon emerald but every battle is a 1v2You s...
3218,NaN,be8mqaTi_DI,Victor Cibrian x Fuerza Regida x Luis R Conriq...,2022-07-04 21:00:36+00:00,UC648rgJOboZlgcDbW00vTSA,Rancho Humilde,10,22.11.07,Rancho Humilde|Legado 7|El De La Guitarra|Fuer...,2256933,597,https://i.ytimg.com/vi/be8mqaTi_DI/default.jpg,False,True,SuscrÃ­bete: https://Rancho.lnk.to/RHYoutube\r...
3219,NaN,14aYHc7ybu0,WE STAYED AT A 1 STAR HOTEL FOR 24 HOURS | coc...,2022-07-05 13:40:04+00:00,UCSGoIq_tVESqNYF1Re-zn1Q,HJ Evelyn,24,22.11.07,hjevelyn|Evelyn ha|Emily ha|erica ha|korean si...,922668,2951,https://i.ytimg.com/vi/14aYHc7ybu0/default.jpg,False,True,never again ahaha.... CHECK OUT OUR MERCH: htt...
3220,NaN,mQ9eFI13NCQ,"I 100%'d Cuphead: The Delicious Last Course, H...",2022-07-04 16:04:33+00:00,UCRgzckrm1Svf-Y_dIWsTPTg,The Andrew Collette Show,20,22.11.07,cuphead|cuphead dlc|cuphead the delicious last...,1176289,620,https://i.ytimg.com/vi/mQ9eFI13NCQ/default.jpg,False,True,My Cuphead: The Delicious Last Course Let's Pl...

### **Задание 2 [1 балл]**

Посмотрите на колонку description .

- **(0.3 балла)** Переведите строки в нижний регистр и обрежьте ненужные пробелы справа и слева.
- **(0.5 балла)** Замените url-адреса в описаниях на специальный тэг \<URL\> (прямо как строчку, "\<URL>").
- **(0.2 балла)** Выведите полностью description для видеоролика с video_id = 'Oxexirlmdig' .

In [ ]:
pattern = r'http\S+' # возможно пригодятся регулярные выражения..

In [ ]:
import re
df['description'] = df['description'].str.lower()
df['description'] = df['description'].apply(lambda x: re.sub(r'http\S+', '<URL>', x) if isinstance(x, str) else x)
pd.set_option('display.max_colwidth', None)
df[df['video_id'] == 'Oxexirlmdig']['description'].to_string()

'12    music line & lyrics : ghetto geasy & majkmusic produced : bigdeal records mix & master: bigdeal recordsavailable on:spotify: <URL> <URL> <URL>'

In [ ]:
pd.set_option('display.max_colwidth', 50)

**music line & lyrics : ghetto geasy
& majkmusic produced : bigdeal records mix & master: bigdeal
recordsavailable on:spotify: **

### **Задание 3 [1 балл]**

Какое максимальное число просмотров (колонка view_count ) у видеороликов, выпущенных во Франции или Италии (в колонке country значениe FR или IT) в июле (колонка publishedAt)?

Необходимо придумать решение в одну строку , используя
для выбора строк несколько условий, объединенных с помощью | вместо or,
& вместо and и ~ вместо not, а также используя функцию isin .

In [ ]:
df[(df['country'].isin(['FR', 'IT']))&(df['publishedAt'].dt.month==7)]['view_count'].max()

82864422

**82864422**

### **Задание 4 [0.5 баллa]**

- **(0.2 балла)** Посмотрите на названия каналов из 17 категории (колонка categoryId). Как вы думаете, что это за категория?
- **(0.3 балла)** Предположим, что
была допущена ошибка, и все видеоролики из 17 категории, относятся к 16
категории. Исправьте нужные значения в колонке categoryId, после чего
выведите все уникальные категории.

**Подсказка**
Обратите внимание, что при выборе полей с помощью оператора
индексирования [] возвращается копия выбранных значений. При попытке
присвоить таким образом новые значения для некоторых полей таблицы,
будет выдано предупреждение. Более надежный способ - использовать
операторы loc и iloc . Подробнее про индексацию и выбор строк можно прочитать здесь .

In [ ]:
df[df['categoryId']==17]['channelTitle']
df.loc[df['categoryId']==17, 'categoryId']=16
df['categoryId'].unique()

array([24, 10,  1, 15, 22, 23, 27, 16, 20, 26, 25,  2, 19, 28])

**спортивные каналы**

### **Задание 5 [0.5 баллa]**

Посмотрите на колонку tags .

- **(0.2 балла)** Замените строки со значением '[none]' на пустую строку.
- **(0.3 балла)** Какой самый популярный тэг? Обратите внимание, что у каждого видеоролика может быть более 1 тэга.

**Подсказка**

Чтобы получить правильное значение, не забудьте обработать множество
тэгов - убрать пробельные символы по краям и привести строки в нижний
регистр.

**Подсказка**

Нужный тэг встречается больше 130 раз.

In [ ]:
df.loc[df['tags']=='[none]', 'tags']=""
def edit(text):
  return text.lower().lstrip().rstrip()
df['tags'].value_counts()[df['tags'].apply(edit).mode()]

**611**

# Часть 2. Визуализация данных (0,5 баллa), кросс-проверка

### Оформление графиков

Важно, чтобы все графики выглядели опрятно и соответствовали следующим правилам:

🔷 Максимально поясняйте, что изображено на графике

```
✅ Добавляйте название (plt.title)
✅ Подписывайте оси (plt.xlabel, plt.ylabel)
✅ Подписывайте единицы измерения на осях
✅ Делайте понятные подписи
```

🔷 Следите за визуальной составляющей графика

```
✅ Подписи нигде не должны заезжать друг на друга
✅ Все линии на графиках должны быть чётко видны
❌ Не используйте похожие цвета или цвета, сливающиеся с фоном
✅ Используйте векторный (pdf/svg) формат при возможности
✅ Ограничивайте диапазоны значений там, где это возможно (например, вероятности можно ограничить диапазоном [0,1])
✅ Для улучшения демонстрации различий можно логарифмировать оси x и/или y (plt.xscale("log"), plt.yscale("log"))
❌ Не рекомендуется использовать 3d графики в презентациях: при возможности изобразите необходимое при помощи нескольких 2d графиков
```

🔷 Учитывайте размеры и вместимость графиков

```
✅ Графики должны быть комфортного для показа размера: все, что необходимо показать, должно быть хорошо видно
✅ Иногда можно разбивать логически график на несколько полотен, если на одно все не умещается
```

Больше примеров Вы можете найти в документации .

In [ ]:
import matplotlib
import matplotlib.pyplot as plt

#отображение графиков в ноутбуке
%matplotlib inline

#для четкой прорисовки графиков - осторожно!!! Может съедать много памяти
#закоменьте эту строку, если это случилось
%config InlineBackend.figure_format = 'svg'

Далее вам нужно построить несколько визуализаций табличных данных о видео, с которыми мы работали в 1 части задания.

**Внимание!**

- Проверьте, что при конвертации в html формат все графики остаются видны.
Это нужно для дальнейшей проверки в проверяющей системе. Проверить это
можно непосредственно загрузив задание в систему и посмотреть на свою
отправленную посылку (как это сделать - можно почитать в туториале о
проверяющей системе)
- При решении заданий вы можете воспользоваться любыми средствами для визуализации.
- Все графики должны выглядеть опрятно и соответствовать правилам, перечисленным в начале Части 2. В случае несоответствия хотя бы 3 пунктам оценка может быть снижена

TODO

### **Задание 1 [0,5 балл]**

Изобразите на одном полотне несколько графиков вида box_plot , отображающие: для каждой страны ( country ) box_plot распределения значения просмотров ( view_count ). Причем нужно это сделать только по тем роликам, по которым комментарии запрещены ( comments_disabled )

Ответьте на вопрос, опираясь на график: в каких двух странах в среднем наибольшее число просмотров?

In [ ]:
filtered=df[df['comments_disabled']==True]
plt.figure(figsize=(10, 10))
filtered.boxplot(column='view_count', by='country')
plt.suptitle('')
plt.title('Распр. кол. просмотров видео с выкл. комм. по странам')
plt.yscale("log")
plt.xlabel('Страна')
plt.ylabel('Количество просмотров')

Text(0, 0.5, 'Количество просмотров')

<Figure size 1000x1000 with 0 Axes>

**Ваш ответ тут:**

# Часть 3. Numpy (6 баллов), сдача в систему проверки

In [ ]:
import numpy as np

**Внимание!**

- Файлы research_functions.py и research_functions_vectorised.py с реализованными функциями необходимо сдать на тестирование в проверяющей системе.

### **Задачи 1-5 [5 баллов]**

Для каждой из задач ниже привидите 2 реализации: одна без использования numpy, а вторая полностью векторизованная ( без использования циклов/map/list comprehension ).
Реализации без использования векторизации нужно записать в файл
research_functions.py, а векторизованные — в файл
research_functions_vectorised.py (см. шаблоны).

**Внимание!**

Векторизованные реализации с использованием циклов/map/list comprehension оцениваются в 0 баллов .

```
*   Невекторизованные варианты оцениваются - по 0.3 балла
*   Векторизованные варианты - по 0.7 балла
```

- **Задача 1** : Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.
**Пример**
Input: x = [1, 2, 2, 4], y = [4, 2, 1, 2]
Output: True

- **Задача 2** : Найти максимальное
прозведение соседних элементов в массиве x, таких что хотя бы один
множитель в произведении делится на 3. Если таких произведений нет, то
вернуть -1.
**Пример**
Input: x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
Output: 12

- **Задача 3** : Дан трёхмерный
массив image, содержащий изображение, размера (height, width,
num_channels), а также вектор весов weights длины num_channels. Сложить
каналы изображения с указанными весами, и вернуть результат в виде
матрицы размера (height, width). Обратите внимание, что в изображении может быть не три канала!
**Пример**
Input: image = [[[1, 1, 1], [2, 2, 2], [3, 3, 3]], [[4, 4, 4], [5, 5, 5], [6, 6, 6]], [[7, 7, 7], [8, 8, 8], [9, 9, 9]]], weights= [1, 2, 3]
Output: [[6, 12, 18], [24, 30, 36], [42, 48, 54]]
**Комментарий**
В примере исходное изображение с тремя каналами, где по всем каналам значения равны [[1, 2, 3], [4, 5, 6], [7, 8, 9]].
После умножения первого канала на вес 1 получим значения для первого канала [[1, 2, 3], [4, 5, 6], [7, 8, 9]].
После умножения второго канала на вес 2 получим значения для второго канала [[2, 4, 6], [8, 10, 12], [14, 16, 18]].
После умножения третьего канала на вес 3 получим значения для третьего канала [[3, 6, 9], [12, 15, 18], [21, 24, 27]].
Если сложить полученное изображение поканально получим [[6, 12, 18], [24, 30, 36], [42, 48, 54]].

- **Задача 4** : Найти скалярное
произведение между векторами x и y, заданными в формате RLE (Run-length
encoding, кодирование длин серий). Каждый закодированный вектор
представлен двумерным массивом, каждая строка которого имеет размерность
2, где первое число - элемент, а второе число - сколько раз элемент
нужно повторить. Например, [[1,2], [2, 3], [3, 1]] соответствует веткору
[1, 1, 2, 2, 2, 3]. В случае несовпадения длин исходных векторов
вернуть -1.
**Пример**
Input: x = [[1, 2], [2, 3], [3, 1]], y = [[1, 1], [0, 5]].
Output: 1
- **Задача 5** : Даны две выборки
объектов - X и Y. Вычислить матрицу косинусных расстояний между
объектами X и Y. Пусть X - матрица n объектов размера (n, d), Y -
матрица из m объектов размера (m, d), тогда матрица косинусных
расстояний M - матрица размера (n, m), где m_ij - косинус угла между i-м
объектом из матрицы Х (i-ая строка) и j-м объектом из матрицы Y (j-ая
строка матрицы Y). Если хотя бы один из векторов равен 0, то косинусное
расстояние определим равным 1.
**Пример**
Input: X = [[0, 0, 0], [1, 0, 0]], Y = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
Output: [[1, 1, 1], [1, 0, 0]]

**Примечание** Можно считать, что все входные данные непустые и коректные.

**Внимание!**

- Следующее задание оценивается по системе кросс-рецензирования .

### **Задача 6 [1 балл]**

- **(0.5 балла)** Для каждой задачи
сравните скорость работы невекторизованной и векторизованной реализации.
Для этого постройте графики времени работы векторизованной и
невекторизованной реализации в зависимости от размера данных ( line plot ). Код генерации данных разных размеров и функция для замера времени работы функций уже написаны.
- **(0.5 баллa)** Сделайте выводы о времени работы функций.

**Внимание!** В текущую директорию
необходимо загрузить файлы research_functions.py и
research_functions_vectorised.py с реализованными функциями. В Google
Colab это можно сделать, нажав на значок "папки" слева, дальше на
"загрузить" (значок листа со стрелкой вверх). Загружать нужно в папку
"sample_data" (она у вас откроется по умолчанию)

In [ ]:
!ls
import time
import numpy as np

import research_functions_vectorised
import research_functions

requirements_2024_25_for_colab_small.txt  sample_data
research_functions.py			  youtube_trending_mediterranean.csv
research_functions_vectorised.py

In [ ]:
# генерация данных

are_multisets_equal_data = []
for n in [10, 100, 1000, 10000]:
    x = np.random.randint(0, 2, n)
    y = np.random.randint(0, 2, n)
    are_multisets_equal_data += [(x, y)]

max_prod_mod_3_data = []
for n in [10, 100, 1000, 10000]:
    x = np.random.randint(1, 100, n)
    max_prod_mod_3_data += [x]

convert_image_data = []
for n in [10, 100, 1000]:
    image = np.random.random((n, n, 10))
    weights = np.random.random(10)
    convert_image_data += [(image, weights)]

rle_scalar_data = []
for n in [10, 100, 1000, 10000]:
    x = np.random.randint(1, 3, (n, 2))
    y = np.random.randint(1, 3, (n, 2))
    shapes = np.random.randint(1, 3, n)
    x[:, 1] = shapes
    y[:, 1] = shapes

    rle_scalar_data += [(x, y)]

cosine_distance_data = []
for n in [10, 100]:
    X = np.random.random((n, n))
    Y = np.random.random((n, n))
    cosine_distance_data += [(X, Y)]

In [ ]:
# функция для подсчета времени работы

def count_time(func, *data):
    tick = time.perf_counter()
    func(*data)
    return time.perf_counter() - tick

In [ ]:
# получим время работы функций

# max_prod_mod_3

max_prod_mod_3_time = []
max_prod_mod_3_vectorised_time = []

for x in max_prod_mod_3_data:
  max_prod_mod_3_time += [count_time(research_functions.max_prod_mod_3, x.tolist())]
  max_prod_mod_3_vectorised_time += [count_time(research_functions_vectorised.max_prod_mod_3, x)]

sizes_max_prod_mod_3 = [10, 100, 1000, 10000]

# are_multisets_equal
are_multisets_equal_time = []
are_multisets_equal_vectorised_time = []

for x, y in are_multisets_equal_data:
    are_multisets_equal_time += [count_time(research_functions.are_multisets_equal, x.tolist(), y.tolist())]
    are_multisets_equal_vectorised_time += [count_time(research_functions_vectorised.are_multisets_equal, x, y)]

sizes_are_multisets_equal = [10, 100, 1000, 10000]

# convert_image
convert_image_time = []
convert_image_vectorised_time = []

for image, weights in convert_image_data:
    convert_image_time += [count_time(research_functions.convert_image, image.tolist(), weights.tolist())]
    convert_image_vectorised_time += [count_time(research_functions_vectorised.convert_image, image, weights)]

sizes_convert_image = [10, 100, 1000]

# rle_scalar
rle_scalar_time = []
rle_scalar_vectorised_time = []

for x, y in rle_scalar_data:
    rle_scalar_time += [count_time(research_functions.rle_scalar, x.tolist(), y.tolist())]
    rle_scalar_vectorised_time += [count_time(research_functions_vectorised.rle_scalar, x, y)]

sizes_rle_scalar = [10, 100, 1000, 10000]

# cosine_distance
cosine_distance_time = []
cosine_distance_vectorised_time = []

for X, Y in cosine_distance_data:
    cosine_distance_time += [count_time(research_functions.cosine_distance, X.tolist(), Y.tolist())]
    cosine_distance_vectorised_time += [count_time(research_functions_vectorised.cosine_distance, X, Y)]

sizes_cosine_distance = [10, 100]

In [ ]:
# ВАШИ ГРАФИКИ ЗДЕСЬ
import matplotlib.pyplot as plt

def plot_in_subplot(ax, sizes, non_vectorised_time, vectorised_time, title):
    ax.plot(sizes, non_vectorised_time, label='Невекторизованная реализация', marker='o', color='red')
    ax.plot(sizes, vectorised_time, label='Векторизованная реализация', marker='o', color='green')
    ax.set_xlabel('Объем данных')
    ax.set_ylabel('Время выполнения (с)')
    ax.set_xscale('log')
    ax.set_title(title)
    ax.legend()
    ax.grid(True)

fig, axs = plt.subplots(3, 2, figsize=(10, 10))

plot_in_subplot(axs[0, 0], sizes_max_prod_mod_3, max_prod_mod_3_time, max_prod_mod_3_vectorised_time, 'Max Prod Mod 3')
plot_in_subplot(axs[0, 1], sizes_are_multisets_equal, are_multisets_equal_time, are_multisets_equal_vectorised_time, 'Are Multisets Equal')
plot_in_subplot(axs[1, 0], sizes_convert_image, convert_image_time, convert_image_vectorised_time, 'Convert Image')
plot_in_subplot(axs[1, 1], sizes_rle_scalar, rle_scalar_time, rle_scalar_vectorised_time, 'RLE Scalar')
plot_in_subplot(axs[2, 0], sizes_cosine_distance, cosine_distance_time, cosine_distance_vectorised_time, 'Cosine Distance')

fig.delaxes(axs[2, 1])
plt.tight_layout()

**Ваш ответ тут:**