# Машинное обучение. ВМК МГУ

# Практическое задание 2: Numpy + pandas + matplotlib

## Уровень: **Базовый (Base)**

# О формате сдачи

🔷 При решении ноутбука используйте данный шаблон

```
✅ Можно добавлять новые ячейки любых типов
❌ Не нужно удалять текстовые ячейки c разметкой частей ноутбука и формулировками заданий
```

🔷 При оценивании задач учитывается код

```
✅ Задания, в которых необходим код, обычно помечаются фразами "Your code here"/"Ваш код" и аналогичными
❌ Ответы на вопросы без сопутствующего кода оцениваются в 0 баллов
❌ Наличе работоспособного кода в ноутбуке, если на сказано иного, обязательно
```

🔷 При оценивании задач учитываются выводы

```
✅ Задания, в которых необходимы выводы, обычно помечаются фразами Вывод"/"Ответ на вопрос"/"Ваш текст" и аналогичными
✅ Обычно выводы подразумевают под собой текстовый ответ (можно писать markdown, latex).
✅ Сопутствующие изображения, графики, таблички - приветствуются!
❌ При отсутствии выводов задание не засчитается на полный балл
```

- Многие из заданий можно выполнить несколькими способами.
Не существуют единственно верного, но попробуйте максимально
задействовать арсенал pandas и ориентируйтесь на простоту и понятность
вашего кода. Не забывайте, что можно гуглить и что-то искать на stackoverflow, например.

# Подготовка рабочей среды

Сначала установим нужные нам версии библиотек. Мы гарантируем, что в данных версиях задание будет корректно отрабатывать.

После установки нужных версий, возможно, нужно перезагрузить среду (runtime), но скорее всего вам это не понадобится

На скачивание файла и установку понадобится не более 5 минут.

**Важно!**

Устанавливать нужные версии нужно каждый раз, когда создается новый
рантайм. Например, если вы 2 часа подряд делаете это задание, то
подготовить библиотеки достаточно 1 раз. Но если вы, например, начали в
понедельник, затем закрыли/выключили ноутбук, то при продолжении в
среду, вам нужно будет запустить рантайм заново и следовательно заново
установить библиотеки.

**Важно!**
Если вы предпочитаете делать практические задания на своем личном ноутбуке, то проверьте, что вы установили рабочее окружение в соответствии с гайдом .pdf)

In [ ]:
# !!! Данный блок будет работать только в Google-Colab !!!
! gdown 10k8Hwn9kpK9SpK4IEj4-EaWQZqgYT5-Q
! pip install -r /content/requirements_2024_25_for_colab_small.txt

Downloading...
From: https://drive.google.com/uc?id=10k8Hwn9kpK9SpK4IEj4-EaWQZqgYT5-Q
To: /content/requirements_2024_25_for_colab_small.txt
100% 375/375 [00:00<00:00, 1.16MB/s]
Collecting catboost==1.2.7 (from -r /content/requirements_2024_25_for_colab_small.txt (line 1))
  Downloading catboost-1.2.7-cp310-cp310-manylinux2014_x86_64.whl.metadata (1.2 kB)
Collecting gdown==5.1.0 (from -r /content/requirements_2024_25_for_colab_small.txt (line 2))
  Downloading gdown-5.1.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: h5py==3.11.0 in /usr/local/lib/python3.10/dist-packages (from -r /content/requirements_2024_25_for_colab_small.txt (line 3)) (3.11.0)
Requirement already satisfied: hyperopt==0.2.7 in /usr/local/lib/python3.10/dist-packages (from -r /content/requirements_2024_25_for_colab_small.txt (line 4)) (0.2.7)
Collecting ipympl==0.9.4 (from -r /content/requirements_2024_25_for_colab_small.txt (line 5))
  Downloading ipympl-0.9.4-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: ipywidgets==7.7.1 in /usr/local/lib/python3.10/dist-packages (from -r /content/requirements_2024_25_for_colab_small.txt (line 6)) (7.7.1)
Collecting lightgbm==4.4.0 (from -r /content/requirements_2024_25_for_colab_small.txt (line 7))
  Downloading lightgbm-4.4.0-py3-none-manylinux_2_28_x86_64.whl.metadata (19 kB)
Requirement already satisfied: matplotlib==3.7.1 in /usr/local/lib/python3.10/dist-packages (from -r /content/requirements_2024_25_for_colab_small.txt (line 8)) (3.7.1)
Requirement already satisfied: matplotlib-inline==0.1.7 in /usr/local/lib/python3.10/dist-packages (from -r /content/requirements_2024_25_for_colab_small.txt (line 9)) (0.1.7)
Requirement already satisfied: numpy==1.26.4 in /usr/local/lib/python3.10/dist-packages (from -r /content/requirements_2024_25_for_colab_small.txt (line 10)) (1.26.4)
Collecting pandas==2.1.4 (from -r /content/requirements_2024_25_for_colab_small.txt (line 11))
  Downloading pandas-2.1.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting pep8==1.7.1 (from -r /content/requirements_2024_25_for_colab_small.txt (line 12))
  Downloading pep8-1.7.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting plotly==5.15.0 (from -r /content/requirements_2024_25_for_colab_small.txt (line 13))
  Downloading plotly-5.15.0-py2.py3-none-any.whl.metadata (7.0 kB)
Collecting pycodestyle==2.12.1 (from -r /content/requirements_2024_25_for_colab_small.txt (line 14))
  Downloading pycodestyle-2.12.1-py2.py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: pytest==7.4.4 in /usr/local/lib/python3.10/dist-packages (from -r /content/requirements_2024_25_for_colab_small.txt (line 15)) (7.4.4)
Collecting scikit-image==0.23.2 (from -r /content/requirements_2024_25_for_colab_small.txt (line 16))
  Downloading scikit_image-0.23.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (14 kB)
Collecting scikit-learn==1.3.2 (from -r /content/requirements_2024_25_for_colab_small.txt (line 17))
  Downloading scikit_learn-1.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Requirement already satisfied: scipy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from -r /content/requirements_2024_25_for_colab_small.txt (line 18)) (1.13.1)
Collecting seaborn==0.13.1 (from -r /content/requirements_2024_25_for_colab_small.txt (line 19))
  Downloading seaborn-0.13.1-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: tqdm==4.66.5 in /usr/local/lib/python3.10/dist-packages (from -r /content/requirements_2024_25_for_colab_small.txt (line 20)) (4.66.5)
Collecting umap-learn==0.5.6 (from -r /content/requirements_2024_25_for_colab_small.txt (line 21))
  Downloading umap_learn-0.5.6-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: xgboost==2.1.1 in /usr/local/lib/python3.10/dist-packages (from -r /content/requirements_2024_25_for_colab_small.txt (line 22)) (2.1.1)
Requirement already satisfied: graphviz in /usr/local/lib/python3.10/dist-packages (from catboost==1.2.7->-r /content/requirements_2024_25_for_colab_small.txt (line 1)) (0.20.3)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from catboost==1.2.7->-r /content/requirements_2024_25_for_colab_small.txt (line 1)) (1.16.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from gdown==5.1.0->-r /content/requirements_2024_25_for_colab_small.txt (line 2)) (4.12.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from gdown==5.1.0->-r /content/requirements_2024_25_for_colab_small.txt (line 2)) (3.16.1)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.10/dist-packages (from gdown==5.1.0->-r /content/requirements_2024_25_for_colab_small.txt (line 2)) (2.32.3)
Requirement already satisfied: networkx>=2.2 in /usr/local/lib/python3.10/dist-packages (from hyperopt==0.2.7->-r /content/requirements_2024_25_for_colab_small.txt (line 4)) (3.3)
Requirement already satisfied: future in /usr/local/lib/python3.10/dist-packages (from hyperopt==0.2.7->-r /content/requirements_2024_25_for_colab_small.txt (line 4)) (1.0.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.10/dist-packages (from hyperopt==0.2.7->-r /content/requirements_2024_25_for_colab_small.txt (line 4)) (2.2.1)
Requirement already satisfied: py4j in /usr/local/lib/python3.10/dist-packages (from hyperopt==0.2.7->-r /content/requirements_2024_25_for_colab_small.txt (line 4)) (0.10.9.7)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.10/dist-packages (from ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (0.2.0)
Requirement already satisfied: ipython<9 in /usr/local/lib/python3.10/dist-packages (from ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (7.34.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (from ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (10.4.0)
Requirement already satisfied: traitlets<6 in /usr/local/lib/python3.10/dist-packages (from ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (5.7.1)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (5.5.6)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (3.6.9)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (3.0.13)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib==3.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 8)) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib==3.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 8)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib==3.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 8)) (4.54.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib==3.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 8)) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib==3.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 8)) (24.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib==3.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 8)) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib==3.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 8)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas==2.1.4->-r /content/requirements_2024_25_for_colab_small.txt (line 11)) (2024.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas==2.1.4->-r /content/requirements_2024_25_for_colab_small.txt (line 11)) (2024.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly==5.15.0->-r /content/requirements_2024_25_for_colab_small.txt (line 13)) (9.0.0)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.10/dist-packages (from pytest==7.4.4->-r /content/requirements_2024_25_for_colab_small.txt (line 15)) (2.0.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in /usr/local/lib/python3.10/dist-packages (from pytest==7.4.4->-r /content/requirements_2024_25_for_colab_small.txt (line 15)) (1.5.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /usr/local/lib/python3.10/dist-packages (from pytest==7.4.4->-r /content/requirements_2024_25_for_colab_small.txt (line 15)) (1.2.2)
Requirement already satisfied: tomli>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from pytest==7.4.4->-r /content/requirements_2024_25_for_colab_small.txt (line 15)) (2.0.2)
Requirement already satisfied: imageio>=2.33 in /usr/local/lib/python3.10/dist-packages (from scikit-image==0.23.2->-r /content/requirements_2024_25_for_colab_small.txt (line 16)) (2.35.1)
Requirement already satisfied: tifffile>=2022.8.12 in /usr/local/lib/python3.10/dist-packages (from scikit-image==0.23.2->-r /content/requirements_2024_25_for_colab_small.txt (line 16)) (2024.9.20)
Requirement already satisfied: lazy-loader>=0.4 in /usr/local/lib/python3.10/dist-packages (from scikit-image==0.23.2->-r /content/requirements_2024_25_for_colab_small.txt (line 16)) (0.4)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn==1.3.2->-r /content/requirements_2024_25_for_colab_small.txt (line 17)) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn==1.3.2->-r /content/requirements_2024_25_for_colab_small.txt (line 17)) (3.5.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.10/dist-packages (from umap-learn==0.5.6->-r /content/requirements_2024_25_for_colab_small.txt (line 21)) (0.60.0)
Collecting pynndescent>=0.5 (from umap-learn==0.5.6->-r /content/requirements_2024_25_for_colab_small.txt (line 21))
  Downloading pynndescent-0.5.13-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.10/dist-packages (from xgboost==2.1.1->-r /content/requirements_2024_25_for_colab_small.txt (line 22)) (2.23.4)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.5.1->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (6.1.12)
Requirement already satisfied: tornado>=4.2 in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.5.1->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (6.3.3)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.10/dist-packages (from ipython<9->ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (71.0.4)
Collecting jedi>=0.16 (from ipython<9->ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5))
  Using cached jedi-0.19.1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython<9->ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (from ipython<9->ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from ipython<9->ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (3.0.48)
Requirement already satisfied: pygments in /usr/local/lib/python3.10/dist-packages (from ipython<9->ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (2.18.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.10/dist-packages (from ipython<9->ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython<9->ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (4.9.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.10/dist-packages (from numba>=0.51.2->umap-learn==0.5.6->-r /content/requirements_2024_25_for_colab_small.txt (line 21)) (0.43.0)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.10/dist-packages (from widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (6.5.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->gdown==5.1.0->-r /content/requirements_2024_25_for_colab_small.txt (line 2)) (2.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown==5.1.0->-r /content/requirements_2024_25_for_colab_small.txt (line 2)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown==5.1.0->-r /content/requirements_2024_25_for_colab_small.txt (line 2)) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown==5.1.0->-r /content/requirements_2024_25_for_colab_small.txt (line 2)) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown==5.1.0->-r /content/requirements_2024_25_for_colab_small.txt (line 2)) (2024.8.30)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown==5.1.0->-r /content/requirements_2024_25_for_colab_small.txt (line 2)) (1.7.1)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython<9->ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (0.8.4)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (3.1.4)
Requirement already satisfied: pyzmq<25,>=17 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (24.0.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (23.1.0)
Requirement already satisfied: jupyter-core>=4.6.1 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (5.7.2)
Requirement already satisfied: nbformat in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (5.10.4)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (6.5.4)
Requirement already satisfied: nest-asyncio>=1.5 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (1.6.0)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (0.21.0)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (1.1.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython<9->ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython<9->ipympl==0.9.4->-r /content/requirements_2024_25_for_colab_small.txt (line 5)) (0.2.13)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.10/dist-packages (from jupyter-core>=4.6.1->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (4.3.6)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.10/dist-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (0.2.4)
Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (4.9.4)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (6.1.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (0.7.1)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (0.4)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (0.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (2.1.5)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets==7.7.1->-r /content/requirements_2024_25_for_colab_small.txt (line 6)) (0.8.4)

Проверим версию библиотеки:

In [ ]:
import catboost
assert(catboost.__version__ == '1.2.7')

Теперь можно приступать к выполнению задания! :)

# О задании

Задание состоит из трех частей, посвященных работе с табличными данными с помощью библиотеки **pandas** , визуализации с помощью библиотек **matplotlib** , **seaborn** , **plotly** и векторным вычислениям с помощью библиотеки **numpy** . Вам предлагается выполнить несколько заданий.

# Часть 1. Pandas [5 баллов], кросс-проверка

В этой части вы отработаете навыки работы с библиотекой **pandas** .

**Подсказка** Если вы еще не прошли выданный воркбук по pandas , то советуем в начале обратиться к нему

Далее потребуется выполнить несколько небольших заданий, покрывающих базовый

1. Новый пункт
2. Новый пункт

функционал библиотеки, который довольно часто пригождается на первичных этапах анализа данных перед обучением ML-моделей.

In [ ]:
import pandas as pd

In [ ]:
!gdown 1sA-fqJb1WxhS_jaYDcIwXWa_b8b2oZJ6

Downloading...
From: https://drive.google.com/uc?id=1sA-fqJb1WxhS_jaYDcIwXWa_b8b2oZJ6
To: /content/youtube_trending_mediterranean.csv
100% 6.22M/6.22M [00:00<00:00, 76.5MB/s]

### **Задание 1 [0.25 баллa]**

Откройте файл с таблицей, загруженной выше, и выведите последние 5 строк.

**Подсказка** Полезные материалы: https://pandas.pydata.org/pandas-docs/stable/getting_started/intro_tutorials/02_read_write.html

Возможно, пригодятся такие функции/методы:

- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html
- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.tail.html#pandas.DataFrame.tail

In [ ]:
df = pd.read_csv("youtube_trending_mediterranean.csv")
df.tail(5)

,country,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description
3216,NaN,eB-A1Y0Dswc,Thank you for watching,2022-07-05T21:18:33Z,UCS5tt2z_DFvG7-39J3aE-bQ,Life of Boris,22,22.11.07,lifeofboris|life of boris|english subtitles|ye...,864216,14431,https://i.ytimg.com/vi/eB-A1Y0Dswc/default.jpg,False,True,New channel: https://www.youtube.com/channel/U...
3217,NaN,KJGTtzccOHU,Pokemon Emerald but every battle is extremely ...,2022-07-05T01:55:10Z,UC0VVYtw21rg2cokUystu2Dw,SmallAnt,20,22.11.07,pokemon|smallant|smallant1|challenge|pokemon c...,1311698,1232,https://i.ytimg.com/vi/KJGTtzccOHU/default.jpg,False,True,Pokemon emerald but every battle is a 1v2You s...
3218,NaN,be8mqaTi_DI,Victor Cibrian x Fuerza Regida x Luis R Conriq...,2022-07-04T21:00:36Z,UC648rgJOboZlgcDbW00vTSA,Rancho Humilde,10,22.11.07,Rancho Humilde|Legado 7|El De La Guitarra|Fuer...,2256933,597,https://i.ytimg.com/vi/be8mqaTi_DI/default.jpg,False,True,SuscrÃ­bete: https://Rancho.lnk.to/RHYoutube\r...
3219,NaN,14aYHc7ybu0,WE STAYED AT A 1 STAR HOTEL FOR 24 HOURS | coc...,2022-07-05T13:40:04Z,UCSGoIq_tVESqNYF1Re-zn1Q,HJ Evelyn,24,22.11.07,hjevelyn|Evelyn ha|Emily ha|erica ha|korean si...,922668,2951,https://i.ytimg.com/vi/14aYHc7ybu0/default.jpg,False,True,never again ahaha.... CHECK OUT OUR MERCH: htt...
3220,NaN,mQ9eFI13NCQ,"I 100%'d Cuphead: The Delicious Last Course, H...",2022-07-04T16:04:33Z,UCRgzckrm1Svf-Y_dIWsTPTg,The Andrew Collette Show,20,22.11.07,cuphead|cuphead dlc|cuphead the delicious last...,1176289,620,https://i.ytimg.com/vi/mQ9eFI13NCQ/default.jpg,False,True,My Cuphead: The Delicious Last Course Let's Pl...

### **Задание 2 [0.25 баллa]**

Сколько в таблице строк и столбцов?

**Подсказка**

Возможно, пригодятся такие функции/методы:

- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.shape.html#pandas.DataFrame.shape

In [ ]:
df.shape[0] #строк

3221

In [ ]:
df.shape[1] #столбцов

15

**3221 строк и 15 столбцов**

### **Задание 3 [0.5 баллa]**

Посмотрите на статистики значений в каждой колонке, отдельно для числовых и для не-числовых признаков.

Ответьте на вопросы:

- Чему равно стандартное отклонение (std) у колонки view_count ?
- Чем равно самое частое (топовое) значение колонки channelTitle ?

**Подсказка**

Возможно, пригодятся такие функции/методы:

- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.describe.html

In [ ]:
df["view_count"].std()
df['channelTitle'].describe()

,channelTitle
count,3221
unique,1344
top,Wimbledon
freq,25

**14008445.725553624, топ channelTitle Wimblendon**

### **Задание 4 [0.5 баллa]**

Ответьте на вопрос: как вы думаете, что это за данные, о чем они?

**Подсказка** Возможно вам понадобится посмотреть на таблицу разными методами, не стесняйтесь этого делать

In [ ]:
df.columns

Index(['country', 'video_id', 'title', 'publishedAt', 'channelId',
       'channelTitle', 'categoryId', 'trending_date', 'tags', 'view_count',
       'comment_count', 'thumbnail_link', 'comments_disabled',
       'ratings_disabled', 'description'],
      dtype='object')

**Судя по названиям столбцов, в табличке
представлены различные сведения о видео, в различное время выходивших в
тренды на ютубе**

### **Задание 5 [0.5 баллa]**

Для скольких стран (колонка country) есть информация о видеороликах в таблице (отсутствие страны НЕ учитывается как +1 значение) ?

**Подсказка**

Базовый функционал, необxодимый для решения, можно найти здесь .

Возможно, пригодятся следующие функции/методы:

- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.nunique.html#pandas.Series.nunique

In [ ]:
df['country'].nunique(True)

19

**19**

### **Задание 6 [0.5 баллa]**

Сколько
есть видеороликов (== записей в таблице) c разрешенными и запрещенными
комментариями? (колонка comments_disabled). Под видеороликом считаем 1
запись в таблице.

**Подсказка**

Возможно, пригодятся следующие функции/методы:

- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.value_counts.html#pandas.Series.value_counts

In [ ]:
df[df['comments_disabled'].isin([True])].shape[0]

28

In [ ]:
df[df['comments_disabled'].isin([False])].shape[0]

3193

**У 28 выключены и у 3193 включены**

### **Задание 7 [0.5 баллa]**

Какое максимальное число просмотров у видеороликов, попавших в таблицу? (колонка view_count)

**Подсказка**

Базовый функционал, необxодимый для решения, можно найти здесь .

Возможно, пригодятся следующие функции/методы:

- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.max.html#pandas.Series.max

In [ ]:
df['view_count'].max()

123034293

**123034293 просмотров**

### **Задание 8 [0.5 баллa]**

Есть ли в данных пропуски? В каких колонках?

**Подсказка**

Про работу с пропущенными значениями можно прочитать здесь .

Возможно, пригодится такая функция: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isnull.html#pandas.DataFrame.isnull

In [ ]:
selected_columns = ['country', 'video_id', 'title', 'publishedAt', 'channelId',
       'channelTitle', 'categoryId', 'trending_date', 'tags', 'view_count',
       'comment_count', 'thumbnail_link', 'comments_disabled',
       'ratings_disabled', 'description']
df[selected_columns].isna().any()

,0
country,True
video_id,False
title,False
publishedAt,False
channelId,False
channelTitle,False
categoryId,False
trending_date,False
tags,False
view_count,False
comment_count,False
thumbnail_link,False
comments_disabled,False
ratings_disabled,False
description,True

**country, description**

### **Задание 9 [0.5 баллa]**

Заполните пропуски пустой строкой для текстовых колонок, и удалите строки с пропусками для колонок с категориальными значениями.

**Подсказка**

Значения **категориальной**
переменной определяют факт принадлежности к какой-то категории,
категорий при этом должно быть ограниченное кол-во сильно меньшее
размера датасета.

**Категориальная переменная** -
колонка, которая имеет ограниченное число уникальных значений. Вообще
говоря, может быть как типа object (текстовые), так и int (численные). В
случае int можно считать, что категории закодированы числами. В таком
случае значения нельзя сравнивать между собой и совершать над ними
арифметические операции. В этом задании категориальные переменные только
типа object.

**Внимание!** Для проверки
корректности выведите кол-во пропусков во всех столбцах и общее кол-во
строк в таблице - должна быть 3021 запись. Ошибка при удалении строк
может привести к неправильному выполнению следующих заданий.

Возможно, пригодятся такие функции:

- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html#pandas.DataFrame.fillna
- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html#pandas.DataFrame.dropna

In [ ]:
df['description'] = df['description'].fillna('')
df = df.dropna(subset=['country'])

In [ ]:
assert df.shape[0] == 3021, "Проверьте правильность выполнения задания."

### **Задание 10 [0.5 баллa]**

Какие
5 роликов набрали в Италии (country='IT') наибольшее число просмотров
(колонка view_count)? В качестве ответа привидите названия каналов с
соответствующими роликами (колонка channelTitle) в порядке убывания
числа просмотров полученных роликов.

**Подсказка**

Для решения воспользуйтесь функцией sort_values .

In [ ]:
print(*[i for i in df[df['country'] == 'IT'].sort_values(by='view_count', ascending=False).head(5)['channelTitle']], sep=', ')

That Little Puff, SMTOWN, Celine & Michiel, SportsNation, BeatboxJCOP

**'That Little Puff, SMTOWN, Celine & Michiel, SportsNation, BeatboxJCOP**

### **Задание 11 [0.5 баллa]**

Какой видеоролик был опубликован в наибольшем кол-ве стран? В качестве ответа привeдите название видеоролика (колонка title).

**Подсказка**

Для решения могут помочь функции groupby и sort_values .

In [ ]:
df.groupby('title')['country'].nunique().sort_values(ascending=False).head(1)

,country
title,
Race Highlights | 2022 British Grand Prix,17

**Race Highlights | 2022 British Grand Prix**

# Часть 2. Визуализация данных [2 балла], кросс-проверка

**Matplotlib** - основная библиотека визуализации двумерных данных на языке python.

Рисунок создается с помощью последовательного вызова функций из модуля pyplot
(создание рисунка, задание области рисования, построение графиков в
области рисования, украшение графика метками). При этом различные
графические элементы рисунка (линии, подписи и т.д.) перекрывают
предыдущие, если они имеют общую площадь.

Основные типы графиков:

- **line plot** — обычный поточечный график, которым можно изображать кривые, соединяющие последовательные точки;
- **histogram** — гистограмма, показывающая распределение некоторое величины;
- **scatter plot** — диаграмма рассеивания, показывающая взаимосвязь двух величин;
- **bar plot** — столбчатая диаграмма, показывающий взаимосвязь количественной величины от категориальной.

### Оформление графиков

Важно, чтобы все графики выглядели опрятно и соответствовали следующим правилам:

🔷 Максимально поясняйте, что изображено на графике

```
✅ Добавляйте название (plt.title)
✅ Подписывайте оси (plt.xlabel, plt.ylabel)
✅ Подписывайте единицы измерения на осях
✅ Делайте понятные подписи
```

🔷 Следите за визуальной составляющей графика

```
✅ Подписи нигде не должны заезжать друг на друга
✅ Все линии на графиках должны быть чётко видны
❌ Не используйте похожие цвета или цвета, сливающиеся с фоном
✅ Используйте векторный (pdf/svg) формат при возможности
✅ Ограничивайте диапазоны значений там, где это возможно (например, вероятности можно ограничить диапазоном [0,1])
✅ Для улучшения демонстрации различий можно логарифмировать оси x и/или y (plt.xscale("log"), plt.yscale("log"))
❌ Не рекомендуется использовать 3d графики в презентациях: при возможности изобразите необходимое при помощи нескольких 2d графиков
```

🔷 Учитывайте размеры и вместимость графиков

```
✅ Графики должны быть комфортного для показа размера: все, что необходимо показать, должно быть хорошо видно
✅ Иногда можно разбивать логически график на несколько полотен, если на одно все не умещается
```

Больше примеров Вы можете найти в документации .

In [ ]:
import matplotlib
import matplotlib.pyplot as plt

#отображение графиков в ноутбуке
%matplotlib inline

#для четкой прорисовки графиков - осторожно!!! Может съедать много памяти
#закоменьте эту строку, если это случилось
%config InlineBackend.figure_format = 'svg'

Далее вам нужно построить несколько визуализаций табличных данных о видео, с которыми мы работали в 1 части задания.

**Внимание!**

- Проверьте, что при конвертации в html формат все графики остаются видны.
Это нужно для дальнейшей проверки в проверяющей системе. Проверить это
можно непосредственно загрузив задание в систему и посмотреть на свою
отправленную посылку (как это сделать - можно почитать в туториале о
проверяющей системе)
- При решении заданий вы можете воспользоваться любыми средствами для визуализации.
- Все графики должны выглядеть опрятно и соответствовать правилам, перечисленным в начале Части 2. В случае несоответствия хотя бы 3 пунктам оценка может быть снижена

### **Задание 1 [0.5 баллa]**

Постройте график (line plot) зависимости кол-ва выпущенных роликов от даты публикации.

**Подсказка**
Не нужно учитывать время публикации, только дату с точностью до дня.

Также обратите внимание, что один и тот же ролик может быть
опубликован в нескольких странах, и ему может соответствовать несколько
строк в таблице. На графике необходимо учесть каждый ролик только 1 раз.

Сначала может понадобиться перевести колонку даты публикации к типу datetime :

In [ ]:
df_new = df.drop_duplicates(subset=['video_id']).copy()

df_new.loc[:, 'publishedAt'] = pd.to_datetime(df_new['publishedAt']).dt.date

In [ ]:
x = df_new['publishedAt']
y = x.value_counts().sort_index()

In [ ]:
import matplotlib.pyplot as plt # или другая любимая библиотека визуализации
import matplotlib.dates as mdates

plt.plot(y.index, y.values)
plt.xticks([y.index[0], y.index[-1]])
plt.title("Зависимость кол-ва выпущенных роликов от даты публикации.")
plt.xlabel('Дата публикации')
plt.ylabel('Кол-во выпущенных роликов')

Text(0, 0.5, 'Кол-во выпущенных роликов')

### **Задание 2 [0.5 баллa]**

Постройте диаграмму (bar plot) кол-ва опубликованных роликов в зависимости от страны.

In [ ]:
df_new = df.groupby('country')['video_id'].nunique().sort_values(ascending=False)
df_new.plot(kind='bar')
plt.title("Кол-во опубликованных роликов в зависимости от страны")
plt.xlabel('Страна')
plt.ylabel('Кол-во выпущенных роликов')

Text(0, 0.5, 'Кол-во выпущенных роликов')

### **Задание 3 [1 балл]**

Постройте график (scatter plot)
зависимости кол-ва комментариев для ролика от кол-ва просмотров для
роликов во Франции (country='FR'). На графике не нужно учитывать ролики с
отключенными комментариями (comments_disabled=True).

Какой характер зависмости получился?

In [ ]:
categories = ['view_count', 'comment_count']
df_new = df[(df['country'] == 'FR') & (df['comments_disabled'] == False)][categories]
x = df_new['comment_count'].tolist()
y = df_new['view_count'].tolist()
plt.scatter(x, y, s = 10)
plt.xscale('log')
plt.yscale('log')
plt.title("Зависимость кол-ва комментариев от просмотров")
plt.xlabel('Кол-во комментариев')
plt.ylabel('Кол-во просмотров')

Text(0, 0.5, 'Кол-во просмотров')

**Ваш ответ тут:**

# Часть 3. Numpy [3 балла], сдача в проверяющую систему

In [ ]:
import numpy as np

**Внимание!**

- Файлы base_functions.py и base_functions_vectorised.py с реализованными функциями необходимо сдать на тестирование в проверяющей системе.

### **Задачи 1-3 [3 баллa]**

Для каждой из задач ниже привидите 2 реализации: одна без использования numpy, а вторая полностью векторизованная ( без использования циклов/map/list comprehension ).
Реализации без использования векторизации нужно записать в файл
base_functions.py, а векторизованные — в файл
base_functions_vectorised.py (см. шаблоны).

**Внимание!**

Векторизованные реализации с использованием циклов/map/list comprehension оцениваются в 0 баллов .

```
*   Невекторизованные варианты оцениваются - по 0.3 балла
*   Векторизованные варианты - по 0.7 балла
```

#### **Задача 1 [0.3 + 0.7 баллов]**

Вам
дан двумерный непустой массив X размера n x m вещественных чисел.
Создайте на его основе массив состоящий: из каждого 4го (начиная с 0го и
до конца) элемента по оси размерности n (axis=0), начиная с 120 до 500
(не включитально) с шагом 5 элементов по оси размерности m (axis=1).

Гарантируется, что m >= 500

\ Пример:

```
  Input: X = [[1, 2, 3, ..., 500], [1, 2, 3, ..., 500], [1, 2, 3, ..., 500], [1, 2, 3, ..., 500], [1, 2, 3, ..., 500]]
  Output: [[121, 126, 131, ..., 496]]
```

#### **Задача 2 [0.3 + 0.7 баллов]**

Вам дан двумерный непустой массив X целых чисел размера n x m.

Посчитайте сумму неотрицательных элементов на главной диагонали
прямоугольной матрицы X. Если неотрицательных элементов на диагонали
нет, то верните -1.

Пример:

```
  Input: X = np.array([[-1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
  Output: 3
```

#### **Задача 1 [0.3 + 0.7 баллов]**

Дан
двумерный непустой массив X вещественных чисел размера n x m. Считая
для каждого столбца отдельно, замените в копии массива те значения,
которые больше 1.5 средних по столбцу или меньше 1/4 среднего по столбцу
на число -1

**Подсказка**

Возможно пригодится функция deepcopy из модуля copy

# **Задание [Bonus][0.5 балла]** , кросс-проверка

Вставьте/придумайте мем про pandas/машинное обучение/Python или просто милую картинку с пандой

**Внимание!** самый простой способ вставить картинку будет через Google Colab (даже если вы изначально делали не в нем). Нажмите на "+ Text" , в появившейся ячейке сделайте прикрепление картинки (как на скринах). Тогда ваша картинка "зашифруется" и будет корректно отображаться при конвертации в html

**Внимание!** Если вы хотите вставить
картинку в других системах работы с ipynb, то можете просто скопировать
картинку в буфер обмена и вставить содержимое в текстовую ячейку (ctrl-c
ctrl-v)

Ваша картинка тут